import type { Metadata } from "next"
import { Unbounded, Oswald } from "next/font/google"
import "./globals.css"

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
})

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/nitx-logo-brand-color-square.svg", type: "image/svg+xml" }],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${unbounded.variable} ${oswald.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
